version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INIDB_ROOT_USERNAME: root
      MONGO_INIDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./database-data:/data/db

  # Mongo Express Service
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example



